# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_File\chat_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Chat(object):
    def setupUi(self, Chat):
        Chat.setObjectName("Chat")
        Chat.resize(500, 550)
        Chat.setStyleSheet("QWidget {\n"
"    background-color: #f8f9ff;\n"
"    font-family: \'Microsoft YaHei UI\', sans-serif;\n"
"}\n"
"\n"
"QLabel#title_label {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    padding: 8px 0;\n"
"    border-bottom: 1px solid #e0e8ff;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    background-color: white;\n"
"    border: 1px solid #e0e8ff;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"    padding: 15px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #dce1e6;\n"
"    border-radius: 15px;\n"
"    padding: 10px 15px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #5b7cfa;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a6cf7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3a5af5;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border: 1px solid #dce1e6;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"#btn_back {\n"
"    background-color: #a0aec0;\n"
"}\n"
"\n"
"#btn_send {\n"
"    font-weight: bold;\n"
"}")
        self.main_layout = QtWidgets.QVBoxLayout(Chat)
        self.main_layout.setContentsMargins(15, 15, 15, 15)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.title_label = QtWidgets.QLabel(Chat)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.main_layout.addWidget(self.title_label)
        self.model_layout = QtWidgets.QHBoxLayout()
        self.model_layout.setObjectName("model_layout")
        self.model_label = QtWidgets.QLabel(Chat)
        self.model_label.setObjectName("model_label")
        self.model_layout.addWidget(self.model_label)
        self.combo_chat_type = QtWidgets.QComboBox(Chat)
        self.combo_chat_type.setObjectName("combo_chat_type")
        self.combo_chat_type.addItem("")
        self.combo_chat_type.addItem("")
        self.model_layout.addWidget(self.combo_chat_type)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.model_layout.addItem(spacerItem)
        self.main_layout.addLayout(self.model_layout)
        self.text_chat = QtWidgets.QTextBrowser(Chat)
        self.text_chat.setObjectName("text_chat")
        self.main_layout.addWidget(self.text_chat)
        self.input_layout = QtWidgets.QHBoxLayout()
        self.input_layout.setObjectName("input_layout")
        self.input_message = QtWidgets.QLineEdit(Chat)
        self.input_message.setMinimumSize(QtCore.QSize(0, 40))
        self.input_message.setObjectName("input_message")
        self.input_layout.addWidget(self.input_message)
        self.btn_send = QtWidgets.QPushButton(Chat)
        self.btn_send.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_send.setObjectName("btn_send")
        self.input_layout.addWidget(self.btn_send)
        self.main_layout.addLayout(self.input_layout)
        self.bottom_layout = QtWidgets.QHBoxLayout()
        self.bottom_layout.setObjectName("bottom_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_layout.addItem(spacerItem1)
        self.btn_back = QtWidgets.QPushButton(Chat)
        self.btn_back.setMinimumSize(QtCore.QSize(80, 35))
        self.btn_back.setObjectName("btn_back")
        self.bottom_layout.addWidget(self.btn_back)
        self.main_layout.addLayout(self.bottom_layout)

        self.retranslateUi(Chat)
        QtCore.QMetaObject.connectSlotsByName(Chat)

    def retranslateUi(self, Chat):
        _translate = QtCore.QCoreApplication.translate
        Chat.setWindowTitle(_translate("Chat", "AI智能对话助手"))
        self.title_label.setText(_translate("Chat", "AI 智能对话助手"))
        self.model_label.setText(_translate("Chat", "对话对象:"))
        self.combo_chat_type.setItemText(0, _translate("Chat", "DeepSeek"))
        self.combo_chat_type.setItemText(1, _translate("Chat", "大喷子"))
        self.input_message.setPlaceholderText(_translate("Chat", "输入您的问题..."))
        self.btn_send.setText(_translate("Chat", "发送"))
        self.btn_back.setText(_translate("Chat", "返回"))
