# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Chat(object):
    def setupUi(self, Chat):
        Chat.setObjectName("Chat")
        Chat.resize(500, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Chat)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(Chat)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.combo_chat_type = QtWidgets.QComboBox(Chat)
        self.combo_chat_type.setObjectName("combo_chat_type")
        self.combo_chat_type.addItem("")
        self.horizontalLayout_3.addWidget(self.combo_chat_type)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.text_chat = QtWidgets.QTextBrowser(Chat)
        self.text_chat.setStyleSheet("background-color: #FFFFFF;\n"
"border: 1px solid #CCCCCC;\n"
"border-radius: 5px;\n"
"font-size: 18px;")
        self.text_chat.setObjectName("text_chat")
        self.verticalLayout.addWidget(self.text_chat)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_message = QtWidgets.QLineEdit(Chat)
        self.input_message.setStyleSheet("border: 1px solid #CCCCCC;\n"
"border-radius: 5px;\n"
"padding: 5px;")
        self.input_message.setObjectName("input_message")
        self.horizontalLayout.addWidget(self.input_message)
        self.btn_send = QtWidgets.QPushButton(Chat)
        self.btn_send.setMinimumSize(QtCore.QSize(60, 0))
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout.addWidget(self.btn_send)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_back = QtWidgets.QPushButton(Chat)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_2.addWidget(self.btn_back)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Chat)
        QtCore.QMetaObject.connectSlotsByName(Chat)

    def retranslateUi(self, Chat):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Chat", "对话对象:"))
        self.combo_chat_type.setItemText(0, _translate("Chat", "DeepSeek"))
        self.btn_send.setText(_translate("Chat", "发送"))
        self.btn_back.setText(_translate("Chat", "返回"))
