# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lenovo\gits\UI_File\floating_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FloatPet(object):
    def setupUi(self, FloatPet):
        FloatPet.setObjectName("FloatPet")
        FloatPet.resize(250, 80)
        FloatPet.setStyleSheet("background-color: transparent;")
        self.verticalLayout = QtWidgets.QVBoxLayout(FloatPet)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drag_area = QtWidgets.QLabel(FloatPet)
        self.drag_area.setMinimumSize(QtCore.QSize(0, 20))
        self.drag_area.setMaximumSize(QtCore.QSize(16777215, 20))
        self.drag_area.setStyleSheet("color: white;\n"
"font-size: 9pt;\n"
"padding-left: 5px;")
        self.drag_area.setObjectName("drag_area")
        self.verticalLayout.addWidget(self.drag_area)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_study = QtWidgets.QPushButton(FloatPet)
        self.btn_study.setMinimumSize(QtCore.QSize(70, 40))
        self.btn_study.setStyleSheet("QPushButton {\n"
"    background-color: #FFD700;\n"
"    border: 1px solid #FFA500;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFEC8B;\n"
"}")
        self.btn_study.setObjectName("btn_study")
        self.horizontalLayout.addWidget(self.btn_study)
        self.btn_translation = QtWidgets.QPushButton(FloatPet)
        self.btn_translation.setMinimumSize(QtCore.QSize(70, 40))
        self.btn_translation.setStyleSheet("QPushButton {\n"
"    background-color: #87CEFA;\n"
"    border: 1px solid #1E90FF;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #B0E2FF;\n"
"}")
        self.btn_translation.setObjectName("btn_translation")
        self.horizontalLayout.addWidget(self.btn_translation)
        self.btn_chat = QtWidgets.QPushButton(FloatPet)
        self.btn_chat.setMinimumSize(QtCore.QSize(70, 40))
        self.btn_chat.setStyleSheet("QPushButton {\n"
"    background-color: #98FB98;\n"
"    border: 1px solid #32CD32;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #C1FFC1;\n"
"}")
        self.btn_chat.setObjectName("btn_chat")
        self.horizontalLayout.addWidget(self.btn_chat)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FloatPet)
        QtCore.QMetaObject.connectSlotsByName(FloatPet)

    def retranslateUi(self, FloatPet):
        _translate = QtCore.QCoreApplication.translate
        self.drag_area.setText(_translate("FloatPet", " 桌面助手 (拖动此处移动)"))
        self.btn_study.setText(_translate("FloatPet", "学习中心"))
        self.btn_translation.setText(_translate("FloatPet", "屏幕翻译"))
        self.btn_chat.setText(_translate("FloatPet", "智能对话"))
