# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_File\floating_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FloatPet(object):
    def setupUi(self, FloatPet):
        FloatPet.setObjectName("FloatPet")
        FloatPet.resize(320, 70)
        FloatPet.setWindowFlags(QtCore.Qt.FramelessWindowHint|QtCore.Qt.WindowStaysOnTopHint|QtCore.Qt.Tool)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FloatPet)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_study = QtWidgets.QPushButton(FloatPet)
        self.btn_study.setMinimumSize(QtCore.QSize(80, 32))
        self.btn_study.setObjectName("btn_study")
        self.horizontalLayout.addWidget(self.btn_study)
        self.btn_translation = QtWidgets.QPushButton(FloatPet)
        self.btn_translation.setMinimumSize(QtCore.QSize(80, 32))
        self.btn_translation.setObjectName("btn_translation")
        self.horizontalLayout.addWidget(self.btn_translation)
        self.btn_chat = QtWidgets.QPushButton(FloatPet)
        self.btn_chat.setMinimumSize(QtCore.QSize(80, 32))
        self.btn_chat.setObjectName("btn_chat")
        self.horizontalLayout.addWidget(self.btn_chat)
        self.btn_screenshot = QtWidgets.QPushButton(FloatPet)
        self.btn_screenshot.setMinimumSize(QtCore.QSize(80, 32))
        self.btn_screenshot.setObjectName("btn_screenshot")
        self.horizontalLayout.addWidget(self.btn_screenshot)

        self.retranslateUi(FloatPet)
        QtCore.QMetaObject.connectSlotsByName(FloatPet)

    def retranslateUi(self, FloatPet):
        _translate = QtCore.QCoreApplication.translate
        FloatPet.setStyleSheet(_translate("FloatPet", "\n"
"                background-color: rgba(250, 250, 250, 230);\n"
"                border-radius: 8px;\n"
"                border: 1px solid #D0D0D0;\n"
"            "))
        self.btn_study.setText(_translate("FloatPet", "反语"))
        self.btn_study.setStyleSheet(_translate("FloatPet", "\n"
"                            QPushButton { \n"
"                                background-color: #FFECB3; /* 柔和的米黄色 */\n"
"                                border: 1px solid #FFD54F; \n"
"                                border-radius: 6px; \n"
"                                color: #333333; \n"
"                                font-size: 8pt; \n"
"                                font-family: \"Microsoft YaHei UI\", sans-serif; \n"
"                                font-weight: normal;\n"
"                                padding: 4px;\n"
"                            } \n"
"                            QPushButton:hover { \n"
"                                background-color: #FFE082; \n"
"                            } \n"
"                            QPushButton:pressed { \n"
"                                background-color: #FFD54F; \n"
"                            }\n"
"                        "))
        self.btn_translation.setText(_translate("FloatPet", "屏翻"))
        self.btn_translation.setStyleSheet(_translate("FloatPet", "\n"
"                            QPushButton { \n"
"                                background-color: #E1F5FE; /* 柔和的淡蓝色 */\n"
"                                border: 1px solid #81D4FA; \n"
"                                border-radius: 6px; \n"
"                                color: #333333; \n"
"                                font-size: 8pt; \n"
"                                font-family: \"Microsoft YaHei UI\", sans-serif; \n"
"                                font-weight: normal;\n"
"                                padding: 4px;\n"
"                            } \n"
"                            QPushButton:hover { \n"
"                                background-color: #B3E5FC; \n"
"                            } \n"
"                            QPushButton:pressed { \n"
"                                background-color: #81D4FA; \n"
"                            }\n"
"                        "))
        self.btn_chat.setText(_translate("FloatPet", "对话"))
        self.btn_chat.setStyleSheet(_translate("FloatPet", "\n"
"                            QPushButton { \n"
"                                background-color: #E8F5E9; /* 柔和的淡绿色 */\n"
"                                border: 1px solid #A5D6A7; \n"
"                                border-radius: 6px; \n"
"                                color: #333333; \n"
"                                font-size: 8pt; \n"
"                                font-family: \"Microsoft YaHei UI\", sans-serif; \n"
"                                font-weight: normal;\n"
"                                padding: 4px;\n"
"                            } \n"
"                            QPushButton:hover { \n"
"                                background-color: #C8E6C9; \n"
"                            } \n"
"                            QPushButton:pressed { \n"
"                                background-color: #A5D6A7; \n"
"                            }\n"
"                        "))
        self.btn_screenshot.setText(_translate("FloatPet", "截屏"))
        self.btn_screenshot.setStyleSheet(_translate("FloatPet", "\n"
"                            QPushButton { \n"
"                                background-color: #FFCCBC; /* 柔和的橙色 */\n"
"                                border: 1px solid #FFAB91; \n"
"                                border-radius: 6px; \n"
"                                color: #333333; \n"
"                                font-size: 9pt; \n"
"                                font-family: \"Microsoft YaHei UI\", sans-serif; \n"
"                                font-weight: normal;\n"
"                                padding: 4px;\n"
"                            } \n"
"                            QPushButton:hover { \n"
"                                background-color: #FFB74D; \n"
"                            } \n"
"                            QPushButton:pressed { \n"
"                                background-color: #FFA726; \n"
"                            }\n"
"                        "))
