# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lenovo\gits\UI_File\screen_translate.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Translation(object):
    def setupUi(self, Translation):
        Translation.setObjectName("Translation")
        Translation.resize(500, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Translation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Translation)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setStyleSheet("font-size: 18px; font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_select_area = QtWidgets.QPushButton(Translation)
        self.btn_select_area.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_select_area.setObjectName("btn_select_area")
        self.verticalLayout.addWidget(self.btn_select_area)
        self.text_result = QtWidgets.QTextEdit(Translation)
        self.text_result.setStyleSheet("background-color: #F8F8F8;\n"
"border: 1px solid #CCCCCC;\n"
"border-radius: 5px;\n"
"padding: 10px;")
        self.text_result.setObjectName("text_result")
        self.verticalLayout.addWidget(self.text_result)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_back = QtWidgets.QPushButton(Translation)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Translation)
        QtCore.QMetaObject.connectSlotsByName(Translation)

    def retranslateUi(self, Translation):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Translation", "屏幕翻译"))
        self.btn_select_area.setText(_translate("Translation", "选择翻译区域"))
        self.btn_back.setText(_translate("Translation", "返回"))
