# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_File/screen_translate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Translation(object):
    def setupUi(self, Translation):
        Translation.setObjectName("Translation")
        Translation.resize(500, 300)
        Translation.setStyleSheet("QWidget {\n"
"    background-color: #f8fafc;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Translation)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Translation)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setStyleSheet("font-size: 22px;\n"
"font-weight: bold;\n"
"color: #1a73e8;\n"
"padding: 10px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_select_area = QtWidgets.QPushButton(Translation)
        self.btn_select_area.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_select_area.setStyleSheet("QPushButton {\n"
"    background-color: #e6f0ff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    color: #2c3e50;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d9e7ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c2d6ff;\n"
"}")
        self.btn_select_area.setObjectName("btn_select_area")
        self.verticalLayout.addWidget(self.btn_select_area)
        self.text_result = QtWidgets.QTextEdit(Translation)
        self.text_result.setStyleSheet("QTextEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #d0e0ff;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    color: #2c3e50;\n"
"    selection-background-color: #e6f0ff;\n"
"    selection-color: #1a73e8;\n"
"}")
        self.text_result.setObjectName("text_result")
        self.verticalLayout.addWidget(self.text_result)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_back = QtWidgets.QPushButton(Translation)
        self.btn_back.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_back.setStyleSheet("QPushButton {\n"
"    background-color: #f0f0f0;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"    padding: 8px 16px;\n"
"    color: #5a6d88;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9;\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Translation)
        QtCore.QMetaObject.connectSlotsByName(Translation)

    def retranslateUi(self, Translation):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Translation", "屏幕翻译"))
        self.btn_select_area.setText(_translate("Translation", "选择翻译区域"))
        self.btn_back.setText(_translate("Translation", "返回"))
