# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lenovo\gits\screen_translate.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScreenTranslate(object):
    def setupUi(self, ScreenTranslate):
        ScreenTranslate.setObjectName("ScreenTranslate")
        ScreenTranslate.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScreenTranslate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(ScreenTranslate)
        self.label_title.setStyleSheet("font-size: 20px;\n"
"font-weight: bold;\n"
"color: #344955;\n"
"padding: 10px;")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_select_area = QtWidgets.QPushButton(ScreenTranslate)
        self.btn_select_area.setStyleSheet("background-color: #F9AA33;\n"
"color: #232F34;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 14px;")
        self.btn_select_area.setObjectName("btn_select_area")
        self.horizontalLayout.addWidget(self.btn_select_area)
        self.btn_translate = QtWidgets.QPushButton(ScreenTranslate)
        self.btn_translate.setStyleSheet("background-color: #344955;\n"
"color: white;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 14px;")
        self.btn_translate.setObjectName("btn_translate")
        self.horizontalLayout.addWidget(self.btn_translate)
        self.btn_back = QtWidgets.QPushButton(ScreenTranslate)
        self.btn_back.setStyleSheet("background-color: #F44336;\n"
"color: white;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 14px;")
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.text_result = QtWidgets.QTextEdit(ScreenTranslate)
        self.text_result.setStyleSheet("background-color: #F5F5F5;\n"
"border: 1px solid #CCCCCC;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 14px;")
        self.text_result.setObjectName("text_result")
        self.verticalLayout.addWidget(self.text_result)

        self.retranslateUi(ScreenTranslate)
        QtCore.QMetaObject.connectSlotsByName(ScreenTranslate)

    def retranslateUi(self, ScreenTranslate):
        _translate = QtCore.QCoreApplication.translate
        self.label_title.setText(_translate("ScreenTranslate", "屏幕翻译"))
        self.btn_select_area.setText(_translate("ScreenTranslate", "选择区域"))
        self.btn_translate.setText(_translate("ScreenTranslate", "翻译"))
        self.btn_back.setText(_translate("ScreenTranslate", "返回"))
        self.text_result.setPlaceholderText(_translate("ScreenTranslate", "翻译结果将显示在这里..."))
