# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lenovo\gits\antonym_learning.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AntonymLearning(object):
    def setupUi(self, AntonymLearning):
        AntonymLearning.setObjectName("AntonymLearning")
        AntonymLearning.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(AntonymLearning)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(AntonymLearning)
        self.label_title.setStyleSheet("font-size: 20px;\n"
"font-weight: bold;\n"
"color: #344955;\n"
"padding: 10px;")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.label_image = QtWidgets.QLabel(AntonymLearning)
        self.label_image.setMinimumSize(QtCore.QSize(300, 200))
        self.label_image.setStyleSheet("background-color: #F5F5F5;\n"
"border: 1px solid #CCCCCC;\n"
"border-radius: 5px;")
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.verticalLayout.addWidget(self.label_image)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_option1 = QtWidgets.QPushButton(AntonymLearning)
        self.btn_option1.setStyleSheet("background-color: #F9AA33;\n"
"color: #232F34;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 14px;")
        self.btn_option1.setObjectName("btn_option1")
        self.gridLayout.addWidget(self.btn_option1, 0, 0, 1, 1)
        self.btn_option2 = QtWidgets.QPushButton(AntonymLearning)
        self.btn_option2.setStyleSheet("background-color: #F9AA33;\n"
"color: #232F34;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 14px;")
        self.btn_option2.setObjectName("btn_option2")
        self.gridLayout.addWidget(self.btn_option2, 0, 1, 1, 1)
        self.btn_option3 = QtWidgets.QPushButton(AntonymLearning)
        self.btn_option3.setStyleSheet("background-color: #F9AA33;\n"
"color: #232F34;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 14px;")
        self.btn_option3.setObjectName("btn_option3")
        self.gridLayout.addWidget(self.btn_option3, 1, 0, 1, 1)
        self.btn_option4 = QtWidgets.QPushButton(AntonymLearning)
        self.btn_option4.setStyleSheet("background-color: #F9AA33;\n"
"color: #232F34;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 14px;")
        self.btn_option4.setObjectName("btn_option4")
        self.gridLayout.addWidget(self.btn_option4, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_submit = QtWidgets.QPushButton(AntonymLearning)
        self.btn_submit.setStyleSheet("background-color: #344955;\n"
"color: white;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-weight: bold;")
        self.btn_submit.setObjectName("btn_submit")
        self.horizontalLayout.addWidget(self.btn_submit)
        self.btn_add_word = QtWidgets.QPushButton(AntonymLearning)
        self.btn_add_word.setStyleSheet("background-color: #4A6572;\n"
"color: white;\n"
"border-radius: 5px;\n"
"padding: 10px;")
        self.btn_add_word.setObjectName("btn_add_word")
        self.horizontalLayout.addWidget(self.btn_add_word)
        self.btn_back = QtWidgets.QPushButton(AntonymLearning)
        self.btn_back.setStyleSheet("background-color: #F44336;\n"
"color: white;\n"
"border-radius: 5px;\n"
"padding: 10px;")
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_result = QtWidgets.QLabel(AntonymLearning)
        self.label_result.setStyleSheet("font-size: 16px;\n"
"color: #344955;\n"
"padding: 10px;\n"
"min-height: 40px;")
        self.label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(AntonymLearning)
        QtCore.QMetaObject.connectSlotsByName(AntonymLearning)

    def retranslateUi(self, AntonymLearning):
        _translate = QtCore.QCoreApplication.translate
        self.label_title.setText(_translate("AntonymLearning", "反语学习 / 单词测试"))
        self.label_image.setText(_translate("AntonymLearning", "单词图片"))
        self.btn_option1.setText(_translate("AntonymLearning", "选项 1"))
        self.btn_option2.setText(_translate("AntonymLearning", "选项 2"))
        self.btn_option3.setText(_translate("AntonymLearning", "选项 3"))
        self.btn_option4.setText(_translate("AntonymLearning", "选项 4"))
        self.btn_submit.setText(_translate("AntonymLearning", "提交答案"))
        self.btn_add_word.setText(_translate("AntonymLearning", "添加到单词本"))
        self.btn_back.setText(_translate("AntonymLearning", "返回"))
        self.label_result.setText(_translate("AntonymLearning", "等待答题..."))
