# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lenovo\gits\chat_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatWindow(object):
    def setupUi(self, ChatWindow):
        ChatWindow.setObjectName("ChatWindow")
        ChatWindow.resize(500, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChatWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_chat = QtWidgets.QTextBrowser(ChatWindow)
        self.text_chat.setStyleSheet("background-color: #F5F5F5;\n"
"border: 1px solid #CCCCCC;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 14px;")
        self.text_chat.setObjectName("text_chat")
        self.verticalLayout.addWidget(self.text_chat)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_message = QtWidgets.QLineEdit(ChatWindow)
        self.input_message.setStyleSheet("border: 1px solid #CCCCCC;\n"
"border-radius: 5px;\n"
"padding: 8px;\n"
"font-size: 14px;")
        self.input_message.setObjectName("input_message")
        self.horizontalLayout.addWidget(self.input_message)
        self.btn_send = QtWidgets.QPushButton(ChatWindow)
        self.btn_send.setStyleSheet("background-color: #344955;\n"
"color: white;\n"
"border-radius: 5px;\n"
"padding: 8px 20px;\n"
"font-size: 14px;")
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout.addWidget(self.btn_send)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_back = QtWidgets.QPushButton(ChatWindow)
        self.btn_back.setStyleSheet("background-color: #F44336;\n"
"color: white;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 14px;")
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)

        self.retranslateUi(ChatWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatWindow)

    def retranslateUi(self, ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        self.input_message.setPlaceholderText(_translate("ChatWindow", "输入消息..."))
        self.btn_send.setText(_translate("ChatWindow", "发送"))
        self.btn_back.setText(_translate("ChatWindow", "返回"))
