# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lenovo\gits\floating_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FloatingWindow(object):
    def setupUi(self, FloatingWindow):
        FloatingWindow.setObjectName("FloatingWindow")
        FloatingWindow.resize(300, 60)
        FloatingWindow.setStyleSheet("background-color: #4A6572;\n"
"border-radius: 10px;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(FloatingWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_antonym = QtWidgets.QPushButton(FloatingWindow)
        self.btn_antonym.setStyleSheet("background-color: #F9AA33;\n"
"color: #232F34;\n"
"border-radius: 5px;\n"
"padding: 8px;\n"
"font-weight: bold;")
        self.btn_antonym.setObjectName("btn_antonym")
        self.horizontalLayout.addWidget(self.btn_antonym)
        self.btn_translate = QtWidgets.QPushButton(FloatingWindow)
        self.btn_translate.setStyleSheet("background-color: #F9AA33;\n"
"color: #232F34;\n"
"border-radius: 5px;\n"
"padding: 8px;\n"
"font-weight: bold;")
        self.btn_translate.setObjectName("btn_translate")
        self.horizontalLayout.addWidget(self.btn_translate)
        self.btn_deepseek_chat = QtWidgets.QPushButton(FloatingWindow)
        self.btn_deepseek_chat.setStyleSheet("background-color: #344955;\n"
"color: white;\n"
"border-radius: 5px;\n"
"padding: 8px;\n"
"font-weight: bold;")
        self.btn_deepseek_chat.setObjectName("btn_deepseek_chat")
        self.horizontalLayout.addWidget(self.btn_deepseek_chat)
        self.btn_spray_chat = QtWidgets.QPushButton(FloatingWindow)
        self.btn_spray_chat.setStyleSheet("background-color: #344955;\n"
"color: white;\n"
"border-radius: 5px;\n"
"padding: 8px;\n"
"font-weight: bold;")
        self.btn_spray_chat.setObjectName("btn_spray_chat")
        self.horizontalLayout.addWidget(self.btn_spray_chat)

        self.retranslateUi(FloatingWindow)
        QtCore.QMetaObject.connectSlotsByName(FloatingWindow)

    def retranslateUi(self, FloatingWindow):
        _translate = QtCore.QCoreApplication.translate
        self.btn_antonym.setText(_translate("FloatingWindow", "反语学习"))
        self.btn_translate.setText(_translate("FloatingWindow", "屏幕翻译"))
        self.btn_deepseek_chat.setText(_translate("FloatingWindow", "DeepSeek"))
        self.btn_spray_chat.setText(_translate("FloatingWindow", "小喷子"))
