# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_File/Reverse_Widget/Finish_Test_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Finish_Test(object):
    def setupUi(self, Finish_Test):
        Finish_Test.setObjectName("Finish_Test")
        Finish_Test.resize(400, 150)
        Finish_Test.setMinimumSize(QtCore.QSize(400, 150))
        Finish_Test.setMaximumSize(QtCore.QSize(400, 150))
        self.Test_result = QtWidgets.QLabel(Finish_Test)
        self.Test_result.setGeometry(QtCore.QRect(120, 20, 141, 41))
        self.Test_result.setAlignment(QtCore.Qt.AlignCenter)
        self.Test_result.setStyleSheet("\n"
"          font-size: 18px;\n"
"          font-weight: bold;\n"
"          color: #2D3748;\n"
"        ")
        self.Test_result.setObjectName("Test_result")
        self.Save_button = QtWidgets.QPushButton(Finish_Test)
        self.Save_button.setGeometry(QtCore.QRect(50, 80, 131, 51))
        self.Save_button.setStyleSheet("\n"
"          QPushButton {\n"
"            background-color: #4C7DE9;\n"
"            color: white;\n"
"            border-radius: 8px;\n"
"            font-size: 16px;\n"
"            font-weight: 600;\n"
"            border: none;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background-color: #3A6AD9;\n"
"          }\n"
"          QPushButton:pressed {\n"
"            background-color: #2A5AC4;\n"
"          }\n"
"        ")
        self.Save_button.setObjectName("Save_button")
        self.Abandon_button = QtWidgets.QPushButton(Finish_Test)
        self.Abandon_button.setGeometry(QtCore.QRect(210, 80, 131, 51))
        self.Abandon_button.setStyleSheet("\n"
"          QPushButton {\n"
"            background-color: #F1F5F9;\n"
"            color: #64748B;\n"
"            border-radius: 8px;\n"
"            font-size: 16px;\n"
"            font-weight: 600;\n"
"            border: 1px solid #E2E8F0;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background-color: #E2E8F0;\n"
"          }\n"
"          QPushButton:pressed {\n"
"            background-color: #CBD5E1;\n"
"          }\n"
"        ")
        self.Abandon_button.setObjectName("Abandon_button")

        self.retranslateUi(Finish_Test)
        QtCore.QMetaObject.connectSlotsByName(Finish_Test)

    def retranslateUi(self, Finish_Test):
        _translate = QtCore.QCoreApplication.translate
        Finish_Test.setWindowTitle(_translate("Finish_Test", "Finish_Test"))
        self.Test_result.setText(_translate("Finish_Test", "Result"))
        self.Save_button.setText(_translate("Finish_Test", "Save"))
        self.Abandon_button.setText(_translate("Finish_Test", "Abandon"))
