# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_File\Reverse_Widget\Finish_Test_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 150)
        Form.setMinimumSize(QtCore.QSize(400, 150))
        Form.setMaximumSize(QtCore.QSize(400, 150))
        self.Save_button = QtWidgets.QPushButton(Form)
        self.Save_button.setGeometry(QtCore.QRect(50, 80, 131, 51))
        self.Save_button.setObjectName("Save_button")
        self.Abandon_button = QtWidgets.QPushButton(Form)
        self.Abandon_button.setGeometry(QtCore.QRect(210, 80, 131, 51))
        self.Abandon_button.setObjectName("Abandon_button")
        self.Test_result = QtWidgets.QLabel(Form)
        self.Test_result.setGeometry(QtCore.QRect(120, 20, 141, 41))
        self.Test_result.setObjectName("Test_result")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Finish_Test"))
        self.Save_button.setText(_translate("Form", "Save"))
        self.Abandon_button.setText(_translate("Form", "Abandon"))
        self.Test_result.setText(_translate("Form", "Result"))
