# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lenovo\gits\UI_File\Reverse_Widget\Language_Learning_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Window(object):
    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(750, 500)
        Main_Window.setMinimumSize(QtCore.QSize(750, 500))
        Main_Window.setMaximumSize(QtCore.QSize(900, 500))
        self.Test_button = QtWidgets.QPushButton(Main_Window)
        self.Test_button.setGeometry(QtCore.QRect(360, 120, 351, 101))
        self.Test_button.setObjectName("Test_button")
        self.Search_button = QtWidgets.QPushButton(Main_Window)
        self.Search_button.setGeometry(QtCore.QRect(360, 240, 351, 101))
        self.Search_button.setObjectName("Search_button")
        self.Brochure_button = QtWidgets.QPushButton(Main_Window)
        self.Brochure_button.setGeometry(QtCore.QRect(360, 360, 351, 101))
        self.Brochure_button.setObjectName("Brochure_button")
        self.Exit_button = QtWidgets.QPushButton(Main_Window)
        self.Exit_button.setGeometry(QtCore.QRect(50, 400, 191, 71))
        self.Exit_button.setObjectName("Exit_button")
        self.Mode_button = QtWidgets.QPushButton(Main_Window)
        self.Mode_button.setGeometry(QtCore.QRect(550, 20, 151, 71))
        self.Mode_button.setObjectName("Mode_button")
        self.Title = QtWidgets.QLabel(Main_Window)
        self.Title.setGeometry(QtCore.QRect(80, 90, 221, 271))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(30)
        font.setBold(True)
        self.Title.setFont(font)
        self.Title.setMouseTracking(False)
        self.Title.setObjectName("Title")

        self.retranslateUi(Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "Main_Window"))
        self.Test_button.setText(_translate("Main_Window", "Test"))
        self.Search_button.setText(_translate("Main_Window", "Search"))
        self.Brochure_button.setText(_translate("Main_Window", "My_Word_Brichure"))
        self.Exit_button.setText(_translate("Main_Window", "Exit"))
        self.Mode_button.setText(_translate("Main_Window", "Mode_Select"))
        self.Title.setText(_translate("Main_Window", "Language\n"
"\n"
" Learning\n"
"\n"
"   Module"))
