# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_File/Reverse_Widget/Language_Learning_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Window(object):
    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(750, 500)
        Main_Window.setMinimumSize(QtCore.QSize(750, 500))
        Main_Window.setMaximumSize(QtCore.QSize(900, 500))
        Main_Window.setStyleSheet("\n"
"    /* 主窗口样式 */\n"
"    QWidget#Main_Window {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"            stop:0 #f5f9ff, stop:1 #e6f0ff);\n"
"        border: 1px solid #d0e0ff;\n"
"        border-radius: 12px;\n"
"    }\n"
"    \n"
"    /* 标题样式 */\n"
"    QLabel#Title {\n"
"        color: #2c3e50;\n"
"        font-family: \'Segoe UI\', Arial, sans-serif;\n"
"        font-weight: 600;\n"
"        background: transparent;\n"
"        text-align: center;\n"
"    }\n"
"    \n"
"    /* 按钮通用样式 */\n"
"    QPushButton {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #4a86e8, stop:1 #3a75d0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 8px;\n"
"        font-family: \'Segoe UI\', Arial, sans-serif;\n"
"        font-size: 16px;\n"
"        font-weight: 600;\n"
"        padding: 8px;\n"
"        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n"
"        min-height: 40px;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #5a96f8, stop:1 #4a85e0);\n"
"        box-shadow: 0 6px 8px rgba(0, 0, 0, 0.15);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #3a75d0, stop:1 #2a65c0);\n"
"        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n"
"    }\n"
"    \n"
"    /* 模式选择按钮特殊样式 */\n"
"    QPushButton#Mode_button {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #6a5acd, stop:1 #5a4abc);\n"
"        font-size: 14px;\n"
"    }\n"
"    \n"
"    /* 退出按钮特殊样式 */\n"
"    QPushButton#Exit_button {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #e74c3c, stop:1 #d62c1a);\n"
"    }\n"
"    \n"
"    /* 主要功能按钮样式 */\n"
"    QPushButton#Test_button, \n"
"    QPushButton#Search_button, \n"
"    QPushButton#Brochure_button {\n"
"        font-size: 18px;\n"
"        min-height: 80px;\n"
"    }\n"
"   ")
        self.bg_decoration1 = QtWidgets.QLabel(Main_Window)
        self.bg_decoration1.setGeometry(QtCore.QRect(20, 20, 100, 100))
        self.bg_decoration1.setStyleSheet("\n"
"        background: transparent;\n"
"        border: 2px solid rgba(74, 134, 232, 0.15);\n"
"        border-radius: 50%;\n"
"    ")
        self.bg_decoration1.setObjectName("bg_decoration1")
        self.bg_decoration2 = QtWidgets.QLabel(Main_Window)
        self.bg_decoration2.setGeometry(QtCore.QRect(650, 400, 70, 70))
        self.bg_decoration2.setStyleSheet("\n"
"        background: transparent;\n"
"        border: 2px solid rgba(74, 134, 232, 0.15);\n"
"        border-radius: 50%;\n"
"    ")
        self.bg_decoration2.setObjectName("bg_decoration2")
        self.Test_button = QtWidgets.QPushButton(Main_Window)
        self.Test_button.setGeometry(QtCore.QRect(360, 120, 351, 101))
        self.Test_button.setObjectName("Test_button")
        self.Search_button = QtWidgets.QPushButton(Main_Window)
        self.Search_button.setGeometry(QtCore.QRect(360, 240, 351, 101))
        self.Search_button.setObjectName("Search_button")
        self.Brochure_button = QtWidgets.QPushButton(Main_Window)
        self.Brochure_button.setGeometry(QtCore.QRect(360, 360, 351, 101))
        self.Brochure_button.setObjectName("Brochure_button")
        self.Exit_button = QtWidgets.QPushButton(Main_Window)
        self.Exit_button.setGeometry(QtCore.QRect(50, 400, 191, 71))
        self.Exit_button.setObjectName("Exit_button")
        self.Mode_button = QtWidgets.QPushButton(Main_Window)
        self.Mode_button.setGeometry(QtCore.QRect(550, 20, 151, 71))
        self.Mode_button.setObjectName("Mode_button")
        self.Title = QtWidgets.QLabel(Main_Window)
        self.Title.setGeometry(QtCore.QRect(80, 90, 221, 271))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.divider = QtWidgets.QLabel(Main_Window)
        self.divider.setGeometry(QtCore.QRect(320, 50, 1, 400))
        self.divider.setStyleSheet("background: rgba(74, 134, 232, 0.2);")
        self.divider.setObjectName("divider")

        self.retranslateUi(Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "Language Learning Module"))
        self.Test_button.setText(_translate("Main_Window", "Test"))
        self.Search_button.setText(_translate("Main_Window", "Search"))
        self.Brochure_button.setText(_translate("Main_Window", "My Word Brochure"))
        self.Exit_button.setText(_translate("Main_Window", "Exit"))
        self.Mode_button.setText(_translate("Main_Window", "Mode Select"))
        self.Title.setText(_translate("Main_Window", "Language\n"
"\n"
" Learning\n"
"\n"
"   Module"))
