# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_File/Reverse_Widget/Progress_Bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Progress_Keeper(object):
    def setupUi(self, Progress_Keeper):
        Progress_Keeper.setObjectName("Progress_Keeper")
        Progress_Keeper.resize(350, 100)
        Progress_Keeper.setMinimumSize(QtCore.QSize(350, 100))
        Progress_Keeper.setMaximumSize(QtCore.QSize(350, 100))
        self.progress_keeper = QtWidgets.QProgressBar(Progress_Keeper)
        self.progress_keeper.setGeometry(QtCore.QRect(70, 50, 221, 31))
        self.progress_keeper.setProperty("value", 0)
        self.progress_keeper.setInvertedAppearance(False)
        self.progress_keeper.setObjectName("progress_keeper")
        self.Annotations = QtWidgets.QLabel(Progress_Keeper)
        self.Annotations.setGeometry(QtCore.QRect(140, 20, 81, 21))
        self.Annotations.setWordWrap(True)
        self.Annotations.setObjectName("Annotations")

        self.retranslateUi(Progress_Keeper)
        QtCore.QMetaObject.connectSlotsByName(Progress_Keeper)

    def retranslateUi(self, Progress_Keeper):
        _translate = QtCore.QCoreApplication.translate
        Progress_Keeper.setWindowTitle(_translate("Progress_Keeper", "Progress_Keeper"))
        self.Annotations.setText(_translate("Progress_Keeper", "Progress"))
