# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_File\Reverse_Widget\Progress_Bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Porgress_Keeper(object):
    def setupUi(self, Porgress_Keeper):
        Porgress_Keeper.setObjectName("Porgress_Keeper")
        Porgress_Keeper.resize(350, 100)
        Porgress_Keeper.setMinimumSize(QtCore.QSize(350, 100))
        Porgress_Keeper.setMaximumSize(QtCore.QSize(350, 100))
        self.progress_keeper = QtWidgets.QProgressBar(Porgress_Keeper)
        self.progress_keeper.setGeometry(QtCore.QRect(70, 50, 221, 31))
        self.progress_keeper.setProperty("value", 24)
        self.progress_keeper.setObjectName("progress_keeper")
        self.Annotations = QtWidgets.QLabel(Porgress_Keeper)
        self.Annotations.setGeometry(QtCore.QRect(140, 20, 81, 21))
        self.Annotations.setObjectName("Annotations")

        self.retranslateUi(Porgress_Keeper)
        QtCore.QMetaObject.connectSlotsByName(Porgress_Keeper)

    def retranslateUi(self, Porgress_Keeper):
        _translate = QtCore.QCoreApplication.translate
        Porgress_Keeper.setWindowTitle(_translate("Porgress_Keeper", "Porgress_Keeper"))
        self.Annotations.setText(_translate("Porgress_Keeper", "Progress"))
