# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lenovo\gits\UI_File\Reverse_Widget\Search_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Word_Search(object):
    def setupUi(self, Word_Search):
        Word_Search.setObjectName("Word_Search")
        Word_Search.resize(600, 300)
        Word_Search.setMinimumSize(QtCore.QSize(600, 300))
        Word_Search.setMaximumSize(QtCore.QSize(600, 300))
        self.Input_word = QtWidgets.QLineEdit(Word_Search)
        self.Input_word.setGeometry(QtCore.QRect(130, 40, 281, 41))
        self.Input_word.setObjectName("Input_word")
        self.Translation = QtWidgets.QLabel(Word_Search)
        self.Translation.setGeometry(QtCore.QRect(90, 100, 171, 61))
        self.Translation.setObjectName("Translation")
        self.Definition = QtWidgets.QLabel(Word_Search)
        self.Definition.setGeometry(QtCore.QRect(50, 180, 421, 91))
        self.Definition.setObjectName("Definition")
        self.Search_word_button = QtWidgets.QPushButton(Word_Search)
        self.Search_word_button.setGeometry(QtCore.QRect(440, 30, 91, 61))
        self.Search_word_button.setObjectName("Search_word_button")
        self.Play_button = QtWidgets.QPushButton(Word_Search)
        self.Play_button.setGeometry(QtCore.QRect(280, 100, 91, 61))
        self.Play_button.setObjectName("Play_button")
        self.Back_button = QtWidgets.QPushButton(Word_Search)
        self.Back_button.setGeometry(QtCore.QRect(490, 210, 75, 61))
        self.Back_button.setObjectName("Back_button")
        self.Add_button = QtWidgets.QPushButton(Word_Search)
        self.Add_button.setGeometry(QtCore.QRect(390, 100, 131, 61))
        self.Add_button.setObjectName("Add_button")

        self.retranslateUi(Word_Search)
        QtCore.QMetaObject.connectSlotsByName(Word_Search)

    def retranslateUi(self, Word_Search):
        _translate = QtCore.QCoreApplication.translate
        Word_Search.setWindowTitle(_translate("Word_Search", "Volcabulary_Search"))
        self.Translation.setText(_translate("Word_Search", "Translation"))
        self.Definition.setText(_translate("Word_Search", "Definiion"))
        self.Search_word_button.setText(_translate("Word_Search", "Search"))
        self.Play_button.setText(_translate("Word_Search", "Voice_Play"))
        self.Back_button.setText(_translate("Word_Search", "Back"))
        self.Add_button.setText(_translate("Word_Search", "Add_to_brochure"))
