# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_File/Reverse_Widget/Search_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Word_Search(object):
    def setupUi(self, Word_Search):
        Word_Search.setObjectName("Word_Search")
        Word_Search.resize(650, 400)
        Word_Search.setMinimumSize(QtCore.QSize(650, 400))
        Word_Search.setMaximumSize(QtCore.QSize(650, 400))
        Word_Search.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f8fafc;\n"
"        font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    }\n"
"    \n"
"    QLineEdit {\n"
"        border: 2px solid #cbd5e1;\n"
"        border-radius: 10px;\n"
"        padding: 10px 15px;\n"
"        font-size: 16px;\n"
"        background: white;\n"
"        color: #1e293b;\n"
"        margin-bottom: 20px;\n"
"    }\n"
"    \n"
"    QLineEdit:focus {\n"
"        border-color: #3b82f6;\n"
"        background-color: #f0f9ff;\n"
"    }\n"
"    \n"
"    QLabel {\n"
"        font-size: 16px;\n"
"        font-weight: 600;\n"
"        color: #334155;\n"
"        background: transparent;\n"
"    }\n"
"    \n"
"    QPushButton {\n"
"        border-radius: 10px;\n"
"        padding: 10px;\n"
"        font-weight: 600;\n"
"        font-size: 14px;\n"
"        color: white;\n"
"        min-height: 50px;\n"
"        transition: all 0.2s ease;\n"
"        border: none;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        transform: translateY(-2px);\n"
"        box-shadow: 0 4px 8px rgba(0,0,0,0.1);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        transform: translateY(0);\n"
"        box-shadow: none;\n"
"    }\n"
"    \n"
"    #Search_word_button {\n"
"        background-color: #3b82f6;\n"
"        font-size: 16px;\n"
"    }\n"
"    \n"
"    #Play_button {\n"
"        background-color: #10b981;\n"
"        font-size: 14px;\n"
"    }\n"
"    \n"
"    #Add_button {\n"
"        background-color: #f59e0b;\n"
"        font-size: 13px;\n"
"    }\n"
"    \n"
"    #Back_button {\n"
"        background-color: #64748b;\n"
"        font-size: 16px;\n"
"    }\n"
"   ")
        self.Input_word = QtWidgets.QLineEdit(Word_Search)
        self.Input_word.setGeometry(QtCore.QRect(110, 40, 300, 61))
        self.Input_word.setObjectName("Input_word")
        self.Translation = QtWidgets.QLabel(Word_Search)
        self.Translation.setGeometry(QtCore.QRect(90, 130, 181, 71))
        self.Translation.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.Translation.setObjectName("Translation")
        self.Definition = QtWidgets.QLabel(Word_Search)
        self.Definition.setGeometry(QtCore.QRect(230, 240, 181, 71))
        self.Definition.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.Definition.setObjectName("Definition")
        self.Search_word_button = QtWidgets.QPushButton(Word_Search)
        self.Search_word_button.setGeometry(QtCore.QRect(460, 30, 100, 70))
        self.Search_word_button.setObjectName("Search_word_button")
        self.Play_button = QtWidgets.QPushButton(Word_Search)
        self.Play_button.setGeometry(QtCore.QRect(340, 130, 100, 70))
        self.Play_button.setObjectName("Play_button")
        self.Back_button = QtWidgets.QPushButton(Word_Search)
        self.Back_button.setGeometry(QtCore.QRect(530, 300, 90, 70))
        self.Back_button.setObjectName("Back_button")
        self.Add_button = QtWidgets.QPushButton(Word_Search)
        self.Add_button.setGeometry(QtCore.QRect(460, 130, 170, 70))
        self.Add_button.setObjectName("Add_button")

        self.retranslateUi(Word_Search)
        QtCore.QMetaObject.connectSlotsByName(Word_Search)

    def retranslateUi(self, Word_Search):
        _translate = QtCore.QCoreApplication.translate
        Word_Search.setWindowTitle(_translate("Word_Search", "Vocabulary Search"))
        self.Input_word.setPlaceholderText(_translate("Word_Search", "Enter a word..."))
        self.Translation.setText(_translate("Word_Search", "Translation"))
        self.Definition.setText(_translate("Word_Search", "Definition"))
        self.Search_word_button.setText(_translate("Word_Search", "Search"))
        self.Play_button.setText(_translate("Word_Search", "Voice Play"))
        self.Back_button.setText(_translate("Word_Search", "Back"))
        self.Add_button.setText(_translate("Word_Search", "Add to Brochure"))
