# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lenovo\gits\UI_File\Reverse_Widget\Test_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Test_Window(object):
    def setupUi(self, Test_Window):
        Test_Window.setObjectName("Test_Window")
        Test_Window.resize(650, 450)
        Test_Window.setMinimumSize(QtCore.QSize(650, 450))
        Test_Window.setMaximumSize(QtCore.QSize(650, 450))
        self.A_button = QtWidgets.QPushButton(Test_Window)
        self.A_button.setGeometry(QtCore.QRect(90, 170, 211, 121))
        self.A_button.setObjectName("A_button")
        self.D_button = QtWidgets.QPushButton(Test_Window)
        self.D_button.setGeometry(QtCore.QRect(320, 300, 211, 121))
        self.D_button.setObjectName("D_button")
        self.C_button = QtWidgets.QPushButton(Test_Window)
        self.C_button.setGeometry(QtCore.QRect(90, 300, 211, 121))
        self.C_button.setObjectName("C_button")
        self.B_button = QtWidgets.QPushButton(Test_Window)
        self.B_button.setGeometry(QtCore.QRect(320, 170, 211, 121))
        self.B_button.setObjectName("B_button")
        self.Pause_button = QtWidgets.QPushButton(Test_Window)
        self.Pause_button.setGeometry(QtCore.QRect(30, 20, 91, 51))
        self.Pause_button.setObjectName("Pause_button")
        self.Play_current_button = QtWidgets.QPushButton(Test_Window)
        self.Play_current_button.setGeometry(QtCore.QRect(150, 70, 251, 61))
        self.Play_current_button.setObjectName("Play_current_button")
        self.Add_button = QtWidgets.QPushButton(Test_Window)
        self.Add_button.setGeometry(QtCore.QRect(450, 70, 131, 61))
        self.Add_button.setObjectName("Add_button")
        self.Test_Progress = QtWidgets.QProgressBar(Test_Window)
        self.Test_Progress.setGeometry(QtCore.QRect(370, 20, 171, 31))
        self.Test_Progress.setProperty("value", 0)
        self.Test_Progress.setObjectName("Test_Progress")

        self.retranslateUi(Test_Window)
        QtCore.QMetaObject.connectSlotsByName(Test_Window)

    def retranslateUi(self, Test_Window):
        _translate = QtCore.QCoreApplication.translate
        Test_Window.setWindowTitle(_translate("Test_Window", "Test_Window"))
        self.A_button.setText(_translate("Test_Window", "A"))
        self.D_button.setText(_translate("Test_Window", "D"))
        self.C_button.setText(_translate("Test_Window", "C"))
        self.B_button.setText(_translate("Test_Window", "B"))
        self.Pause_button.setText(_translate("Test_Window", "Pause"))
        self.Play_current_button.setText(_translate("Test_Window", "Current_Voice"))
        self.Add_button.setText(_translate("Test_Window", "Add_to_brochure"))
