# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_File/Reverse_Widget/Test_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Test_Window(object):
    def setupUi(self, Test_Window):
        Test_Window.setObjectName("Test_Window")
        Test_Window.resize(650, 450)
        Test_Window.setMinimumSize(QtCore.QSize(650, 450))
        Test_Window.setMaximumSize(QtCore.QSize(650, 450))
        Test_Window.setStyleSheet("QWidget {\n"
"    background-color: #f8fafc;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-weight: 500;\n"
"    color: #2c3e50;\n"
"    background-color: #e6f0ff;\n"
"    min-height: 30px;\n"
"    box-shadow: 0 2px 4px rgba(0,0,0,0.05);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d9e7ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c2d6ff;\n"
"    box-shadow: inset 0 1px 3px rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"QPushButton#Play_current_button, \n"
"QPushButton#Add_button {\n"
"    background-color: #e0eeff;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton#A_button, QPushButton#B_button,\n"
"QPushButton#C_button, QPushButton#D_button {\n"
"    font-size: 36px;\n"
"    font-weight: 700;\n"
"    background-color: #f0f7ff;\n"
"    color: #000000;  /* 修改为黑色 */\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 1px solid #cce0ff;\n"
"    border-radius: 6px;\n"
"    background: white;\n"
"    text-align: center;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4d94ff;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel#Time_keeper {\n"
"    font-family: \'Lucida Sans Typewriter\', monospace;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    color: #4d94ff;\n"
"    background: transparent;\n"
"}")
        self.A_button = QtWidgets.QPushButton(Test_Window)
        self.A_button.setGeometry(QtCore.QRect(80, 170, 211, 121))
        self.A_button.setObjectName("A_button")
        self.D_button = QtWidgets.QPushButton(Test_Window)
        self.D_button.setGeometry(QtCore.QRect(360, 300, 211, 121))
        self.D_button.setObjectName("D_button")
        self.C_button = QtWidgets.QPushButton(Test_Window)
        self.C_button.setGeometry(QtCore.QRect(80, 300, 211, 121))
        self.C_button.setObjectName("C_button")
        self.B_button = QtWidgets.QPushButton(Test_Window)
        self.B_button.setGeometry(QtCore.QRect(360, 170, 211, 121))
        self.B_button.setObjectName("B_button")
        self.Pause_button = QtWidgets.QPushButton(Test_Window)
        self.Pause_button.setGeometry(QtCore.QRect(30, 20, 91, 51))
        self.Pause_button.setObjectName("Pause_button")
        self.Play_current_button = QtWidgets.QPushButton(Test_Window)
        self.Play_current_button.setGeometry(QtCore.QRect(80, 90, 251, 61))
        self.Play_current_button.setObjectName("Play_current_button")
        self.Add_button = QtWidgets.QPushButton(Test_Window)
        self.Add_button.setGeometry(QtCore.QRect(400, 90, 131, 61))
        self.Add_button.setObjectName("Add_button")
        self.Test_Progress = QtWidgets.QProgressBar(Test_Window)
        self.Test_Progress.setGeometry(QtCore.QRect(360, 30, 171, 31))
        self.Test_Progress.setProperty("value", 0)
        self.Test_Progress.setObjectName("Test_Progress")
        self.Time_keeper = QtWidgets.QLabel(Test_Window)
        self.Time_keeper.setGeometry(QtCore.QRect(230, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(-1)
        self.Time_keeper.setFont(font)
        self.Time_keeper.setObjectName("Time_keeper")

        self.retranslateUi(Test_Window)
        QtCore.QMetaObject.connectSlotsByName(Test_Window)

    def retranslateUi(self, Test_Window):
        _translate = QtCore.QCoreApplication.translate
        Test_Window.setWindowTitle(_translate("Test_Window", "Test_Window"))
        self.A_button.setText(_translate("Test_Window", "A"))
        self.D_button.setText(_translate("Test_Window", "D"))
        self.C_button.setText(_translate("Test_Window", "C"))
        self.B_button.setText(_translate("Test_Window", "B"))
        self.Pause_button.setText(_translate("Test_Window", "Pause"))
        self.Play_current_button.setText(_translate("Test_Window", "Current_Voice"))
        self.Add_button.setText(_translate("Test_Window", "Add_to_brochure"))
        self.Time_keeper.setText(_translate("Test_Window", "00:00"))
