# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_File/Reverse_Widget/Word_Bank_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_My_Word_Brochure(object):
    def setupUi(self, My_Word_Brochure):
        My_Word_Brochure.setObjectName("My_Word_Brochure")
        My_Word_Brochure.resize(300, 650)
        My_Word_Brochure.setMinimumSize(QtCore.QSize(300, 650))
        My_Word_Brochure.setMaximumSize(QtCore.QSize(300, 650))
        My_Word_Brochure.setStyleSheet("QWidget {\n"
"    background-color: #f8fafc;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"/* 列表样式 */\n"
"QListWidget {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #d0e0ff;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    color: #2c3e50;\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #e8f0ff;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #e6f0ff;\n"
"    color: #1a73e8;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* 按钮通用样式 */\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: 500;\n"
"    color: #2c3e50;\n"
"    background-color: #e6f0ff;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d9e7ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c2d6ff;\n"
"}\n"
"\n"
"/* 特殊按钮样式 */\n"
"QPushButton#Play_button {\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    background-color: #e0eeff;\n"
"}\n"
"\n"
"QPushButton#Load_button,\n"
"QPushButton#Back_button {\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"/* 标签样式 */\n"
"QLabel#Current_chosen_word {\n"
"    font-size: 20px;\n"
"    font-weight: 600;\n"
"    color: #1a73e8;\n"
"    background: transparent;\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.Word_bank = QtWidgets.QListWidget(My_Word_Brochure)
        self.Word_bank.setGeometry(QtCore.QRect(30, 200, 231, 361))
        self.Word_bank.setObjectName("Word_bank")
        self.Back_button = QtWidgets.QPushButton(My_Word_Brochure)
        self.Back_button.setGeometry(QtCore.QRect(180, 580, 81, 51))
        self.Back_button.setObjectName("Back_button")
        self.Current_chosen_word = QtWidgets.QLabel(My_Word_Brochure)
        self.Current_chosen_word.setGeometry(QtCore.QRect(40, 40, 221, 61))
        self.Current_chosen_word.setWordWrap(True)
        self.Current_chosen_word.setObjectName("Current_chosen_word")
        self.Play_button = QtWidgets.QPushButton(My_Word_Brochure)
        self.Play_button.setGeometry(QtCore.QRect(50, 120, 201, 61))
        self.Play_button.setObjectName("Play_button")
        self.Load_button = QtWidgets.QPushButton(My_Word_Brochure)
        self.Load_button.setGeometry(QtCore.QRect(30, 580, 111, 51))
        self.Load_button.setObjectName("Load_button")

        self.retranslateUi(My_Word_Brochure)
        QtCore.QMetaObject.connectSlotsByName(My_Word_Brochure)

    def retranslateUi(self, My_Word_Brochure):
        _translate = QtCore.QCoreApplication.translate
        My_Word_Brochure.setWindowTitle(_translate("My_Word_Brochure", "Word_Brochure"))
        self.Back_button.setText(_translate("My_Word_Brochure", "Back"))
        self.Current_chosen_word.setText(_translate("My_Word_Brochure", "Current_chosen_word"))
        self.Play_button.setText(_translate("My_Word_Brochure", "Standard_Voice"))
        self.Load_button.setText(_translate("My_Word_Brochure", "Load_Brochure"))
