# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_File\Reverse_Widget\Word_Bank_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_My_Word_Brochure(object):
    def setupUi(self, My_Word_Brochure):
        My_Word_Brochure.setObjectName("My_Word_Brochure")
        My_Word_Brochure.resize(300, 650)
        My_Word_Brochure.setMinimumSize(QtCore.QSize(300, 650))
        My_Word_Brochure.setMaximumSize(QtCore.QSize(300, 650))
        self.Word_bank = QtWidgets.QListWidget(My_Word_Brochure)
        self.Word_bank.setGeometry(QtCore.QRect(30, 260, 231, 301))
        self.Word_bank.setObjectName("Word_bank")
        self.Back_button = QtWidgets.QPushButton(My_Word_Brochure)
        self.Back_button.setGeometry(QtCore.QRect(200, 580, 81, 51))
        self.Back_button.setObjectName("Back_button")
        self.Current_chosen_word = QtWidgets.QLabel(My_Word_Brochure)
        self.Current_chosen_word.setGeometry(QtCore.QRect(80, 70, 151, 61))
        self.Current_chosen_word.setObjectName("Current_chosen_word")
        self.Play_button = QtWidgets.QPushButton(My_Word_Brochure)
        self.Play_button.setGeometry(QtCore.QRect(50, 160, 201, 61))
        self.Play_button.setObjectName("Play_button")

        self.retranslateUi(My_Word_Brochure)
        QtCore.QMetaObject.connectSlotsByName(My_Word_Brochure)

    def retranslateUi(self, My_Word_Brochure):
        _translate = QtCore.QCoreApplication.translate
        My_Word_Brochure.setWindowTitle(_translate("My_Word_Brochure", "Word_Brochure"))
        self.Back_button.setText(_translate("My_Word_Brochure", "Back"))
        self.Current_chosen_word.setText(_translate("My_Word_Brochure", "Current_chosen_word"))
        self.Play_button.setText(_translate("My_Word_Brochure", "Standard_Voice"))
